server:
  port: 8080

jwt:
  secret:
    key: "IzcFtBQk1g0o1t3AIPdrVZUw0mBsdfmcMmBS2hX5zFKrJrnogQp36jf1aDjVlgiFXkT8FgQ4u4RKs64OCqO1x52IPlwj6ZJOCLuVWBhkvuqRzAffhSYokAStN61uHNSKeirKriwpCWyhm2qFbKadxEGsosH6V1YDQy2PuoaQ6oqshhxqlwEkPIbhrgfNSxZW0bgrrseScJHYTmvBaabMh4HxML3MEhJAMCmkGbfEcp76RsGIDEiWPkHAl9NGmaTm"

spring:
  cloud:
    gateway:
      routes:
        - id: auth_service_route
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
          filters:
            - AuthenticationFilter # O filtro também se aplica aqui agora

        - id: tenant_service_route
          uri: lb://tenant-service
          predicates:
            - Path=/api/v1/tenants/**
          filters:
            - AuthenticationFilter