server:
  port: 8080

jwt:
  secret: "6D5A7134743777217A25432A462D4A614E645267556B58703273357638792F42"

spring:
  cloud:
    gateway:
      routes:
        - id: tenant_service_route
          uri: lb://TENANT-SERVICE
          predicates:
            - Path=/api/v1/tenants/**

        - id: auth_service_route
          uri: lb://auth-service
          predicates:
            - Path=/auth/**