server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
      routes:
        - id: tenant_service_route
          uri: lb://TENANT-SERVICE
          predicates:
            - Path=/api/v1/tenants/**

        # ROTA CORRIGIDA PARA O AUTH-SERVICE
        - id: auth_service_route
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/auth/** # <-- CORRIGIDO