server:
  port: 8080

spring:
  cloud:
    gateway:
      # Desabilita a criação de rotas automáticas baseadas no Discovery
      discovery:
        locator:
          enabled: false # <-- Altere esta linha
      # A partir de agora, APENAS as rotas abaixo serão consideradas
      routes:
        - id: tenant_service_route
          uri: lb://TENANT-SERVICE
          predicates:
            - Path=/api/v1/tenants/**

        - id: auth_service_route
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**